### PR TITLE
V5

### PR DESCRIPTION
**Pull request by Okipa**
* Added support for Laravel 9
* Dropped support for Laravel 7 and earlier versions
* Added support for PHP 8.1
* Dropped support for PHP 8.0 and earlier versions
* Added `livewire/livewire` dependency as the package is now based on it
* Removed `okipa/laravel-html-helper` dependency
* Replaced `phpcs/phpcbf` by `laravel/pint`
* Added several features :
  * New SPA behaviour
  * New filters ability
  * Head actions (replacing routes declarations)
  * New bulk actions ability
  * Row actions (replacing routes declarations)
  * New ability to search from closure
  * New ability to sort from closure
  * New column actions ability
  * New ability to use built-in column formatters and to create custom ones
  * New drag-and-drop reordering ability

:point_right: [See the upgrade guide](https://github.com/Okipa/laravel-table/blob/v5/docs/upgrade-guides/from-v4-to-v5.md)

### CODE REVIEW

**Comment by RSickenberg** [comment]
I love the commits messages 😄

**Comment by Okipa** [comment]
@RSickenberg, here are some serious WIP commits here ! 🛠️

**Comment by RSickenberg** [comment]
I never took the WIP this seriously until now! 💪🏼 , keep the good work!

**Comment by szepeviktor** [comment]
Would you welcome a `sed` command that patches Larastan in CI?

**Comment by szepeviktor** [comment]
Here you are.

```bash
sed -i -e 's#.*protected \$enablesPackageDiscoveries.*#&\nprotected function overrideApplicationBindings($app){return["livewire"=>"Livewire\\\\LivewireManager"];}#' vendor/nunomaduro/larastan/src/ApplicationResolver.php
```

**Comment by szepeviktor** [comment]
💡 One of your computers has a non-GitHub email address set in `git`.

**Comment by szepeviktor** [comment]
> Target class [livewire] does not exist.

This branch also has this error.

https://github.com/Okipa/laravel-table/pull/98#issuecomment-1230309188 👀

**Comment by Okipa** [comment]
@szepeviktor, Yes, this is still the same unfixed Issue, unfortunately nor Larastan or Livewire opened discussions did got answers allowing to fix it.

**Comment by szepeviktor** [comment]
Changing the order of service provider registration would solve it.

**Comment by Okipa** [comment]
> Changing the order of service provider registration would solve it.

In the `TestCase`? I tested that and it didn't change anything unfortunately.

Livewire is loaded before Laravel Table currently => https://github.com/Okipa/laravel-table/blob/v5/tests/TestCase.php#L46

**Comment by szepeviktor** [comment]
> Livewire is loaded before Laravel Table currently

Yes. It **seems** like.
But the stack trace tells otherwise: https://github.com/Okipa/laravel-table/pull/98#issuecomment-1230309188

**Comment by Okipa** [comment]
> Yes. It **seems** like. But the stack trace tells otherwise: [#98 (comment)](https://github.com/Okipa/laravel-table/pull/98#issuecomment-1230309188)

Well, it seems that I have no way to control the order of the service providers registration, isn't it ?

**Comment by szepeviktor** [comment]
I was researching it without results.
There must be a Laravel forum where there are people with knowledge of Laravel internals.

**Comment by szepeviktor** [comment]
This would patch Larastan
https://github.com/Okipa/laravel-table/pull/81#issuecomment-1229552922
until you reverse the order of service provider loading.

**Pull request merged**
