### PR TITLE
Improve PHPStan config

### PR DESCRIPTION
**Pull request by szepeviktor**
I think it removes traces of a copy-paste.

### CODE REVIEW

**Comment by Okipa** [comment]
@szepeviktor, it is default config file provided by Larastan : https://github.com/nunomaduro/larastan

**Comment by szepeviktor** [comment]
> it is default config file provided by Larastan

That is sad.

**Comment by Okipa** [comment]
I prefer to let it as is and I has to ignore some false positive.

Thanks anyway for your PR 👍

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/larastan/pull/1347 👀

**Pull request closed without merging**
